version: '3'

services:
    front:
        build: 
            context: './dash/docker'
            dockerfile: './Dockerfile'
        volumes:
            - '${PWD}/dash/../data:/app/data'
            - '${PWD}/dash:/app/work'
        ports:
            - '8050:8050'
              #        depends_on:
              #- 'redis'
              #    redis:
              #        image: 'redis:latest'
              #        volumes:
              #            - "redis:/data
              #
        depends_on:
            - ml_worker
    red:
        image: 'redis:latest'
        ports:
            - "6379:6379"
    rabbit:
        image: 'rabbitmq:latest'
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
              #
    ml_worker:
        build:
            context: './dash/docker'
            dockerfile: './Dockerfile'
        volumes:
            - '${PWD}/dash/../data:/app/data'
            - '${PWD}/dash:/app/work'
        
        environment:
            - RABBITMQ_HOST=rabbit
            - RABBITMQ_USERNAME=gues
            - RABBITMQ_PASSWORD=gues
            - RABBITMQ_PORT=5672
        depends_on:
            - rabbit
            - red
        command: celery -A "ml_tasks" worker --loglevel=DEBUG

              
              #        #    ml:
        #        build: './ml_backend/docker/'
        #        ulimits:
        #            memlock: -1
        #            stack: 67108864
        #        volumes:
        #            - '${PWD}/ml_backend:/work/'
        #        ports:
        #            - '8006:8000'
        #        shm_size: '1g'
        #        runtime: nvidia
        #        environment:
        #            NVIDIA_VISIBLE_DEVICES: all
        #            NVIDIA_DRIVER_CAPABILITIES: all
        #        deploy:
        #            resources:
        #                reservations:
        #                    devices:
        #                        - capabilities:
        #                            - gpu
        #
volumes:
    redis: {}
